framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - App\Shared\Infrastructure\Messenger\Middleware\LoggingMessengerMiddleware

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            App\Shared\Application\Message\CreateJobMessage: sync
            App\Shared\Application\Message\ArchiveAlbumMessage: sync
            App\Shared\Application\Message\LinkSearchMessage: sync
            App\Shared\Application\Message\TagAudioMessage: sync
            App\Shared\Application\Event\LinksFoundEvent: sync
            App\Shared\Application\Event\TrackCreatedEvent: sync
            App\Shared\Application\Event\JobFailedEvent: sync
            App\Shared\Application\Event\AudioDownloadedEvent: sync
            App\Shared\Application\Event\AudioTaggedEvent: sync
            App\Shared\Application\Event\AlbumArchivedEvent: sync
            App\Shared\Application\Event\TrackFailedEvent: sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
